In [1]:
import matplotlib as mpl
import matplotlib.pyplot as plt
%matplotlib inline
import numpy as np
import sklearn
import pandas as pd
import os
import sys
import time
import tensorflow as tf

from tensorflow import keras

print(tf.__version__)

2.2.0-rc2


In [2]:
#一元函数近似求导
def f(x):
    return 3. * x ** 2 + 2. * x - 1
def approximae_derivative(f,x,eps=1e-3):
    return (f(x+eps)-f(x-eps))/(2.*eps)

print(approximae_derivative(f,1.))

7.999999999999119


In [3]:
#
def g(x1,x2):
    return (x1 + 5) * (x2 ** 2)
def approximae_gradient(g,x1,x2,eps=1e-3):
    dg_x1 = approximae_derivative(lambda x:g(x,x2),x1,eps)
    dg_x2 = approximae_derivative(lambda x:g(x1,x),x2,eps)
    return dg_x1,dg_x2
print(approximae_gradient(g,2.,3.))

(8.999999999993236, 41.999999999994486)


In [7]:
x1 = tf.Variable(2.0)
x2 = tf.Variable(3.0)
#with tf.GradientTape(persistent=True) as tape:
with tf.GradientTape() as tape:
    tape.watch(x1)
    tape.watch(x2)
    z = g(x1,x2)

#dz_x1 = tape.gradient(z,x1)
#dz_x2 = tape.gradient(z,x2)

dz_x1x2 = tape.gradient(z,[x1,x2])

print(dz_x1x2)
#del tape
"""
try:
    dz_x2 = tape.gradient(z,x2)
except RuntimeError as ex:
    print(ex)
"""

[<tf.Tensor: shape=(), dtype=float32, numpy=9.0>, <tf.Tensor: shape=(), dtype=float32, numpy=42.0>]


'\ntry:\n    dz_x2 = tape.gradient(z,x2)\nexcept RuntimeError as ex:\n    print(ex)\n'

In [9]:
x = tf.Variable(5.0)
with tf.GradientTape() as tape:
    z1 = 3*x
    z2 = x**2
tape.gradient([z1,z2],x) 

<tf.Tensor: shape=(), dtype=float32, numpy=13.0>

In [15]:
#二阶导数
x1 = tf.Variable(2.0)
x2 = tf.Variable(3.0)
with tf.GradientTape(persistent=True) as outer_tape:
    with tf.GradientTape(persistent=True) as inner_tape:
        z=g(x1,x2)
    inner_grads = inner_tape.gradient(z,[x1,x2])
outer_grads = [outer_tape.gradient(inner_grads,[x1,x2]) for inner_grad in inner_grads]
print(outer_grads)
del inner_tape
del outer_tape

[[<tf.Tensor: shape=(), dtype=float32, numpy=6.0>, <tf.Tensor: shape=(), dtype=float32, numpy=20.0>], [<tf.Tensor: shape=(), dtype=float32, numpy=6.0>, <tf.Tensor: shape=(), dtype=float32, numpy=20.0>]]
